### ISSUE TITLE
Waveshare_4_3

### ISSUE THREAD

**Issue by ojaksch** [G6EJD/ESP32-e-Paper-Weather-Display#118]
I'd love to see this working on a Waveshare_4_3 with a resoultuion of 800x600 pixels.

**Comment by G6EJD** [comment]
To be honest I’ve long since given up on that display as it was so unreliable and used a (relative) lot of power in sleep mode. The concept is good but they (WS) failed to release a firmware update that addressed the issues with the display driver.
There would be a lot of work to make the conversion and done of it won’t translate, sorry.

**Comment by ojaksch** [comment]
Okay, no problem at all. Good to know that's a unreliable device, at least for this project. Will gather a 4.2 and retry.
Thanks for listenig.

**Comment by G6EJD** [comment]
4.2” is amongst the best, it takes just 2-secs to refresh and of course takes no power in sleep mode.
