### ISSUE TITLE
Waveshare 3.7 sleep code wrong

### ISSUE THREAD

**Issue by grahamwhaley** [G6EJD/ESP32-e-Paper-Weather-Display#217]
It looks like I messed up my re-written 'do not wake up overnight' code when I did the Waveshare 3.7" display with the firebeetle.

[this code](https://github.com/G6EJD/ESP32-e-Paper-Weather-Display/blob/master/examples/Waveshare_3_7/Waveshare_3_7.ino#LL169C1-L169C53) looks like it is core to the issue, given both those variables are in effect statics!

`  if (WakeupTime < SleepTime ) {  //Wake up tomorrow`

I only noticed this once I'd finally (over a year later) built myself a physical unit to hang on the wall, and noticed the updates were definitely not doing what I expected! I think I must have had a brain fart when I wrote that code ;-)

I'll try to look at and fix this in the next few days - feel free to assign the open Issue to me!

**Comment by G6EJD** [comment]
Yes it passes the tests every hour!

it needs either to be using UNIX time or the tests need to be a lot more comprehensive.

Plus the RC based ESP32 internal clock is notoriously slow or fast so although you may expect it to wake in say 8-hours sone devices may wake early or late. The difficult one to solve is waking early so that it does not invoke another long sleep.
