### ISSUE TITLE
Problem with contrast

### ISSUE THREAD

**Issue by Stebe242** [G6EJD/ESP32-e-Paper-Weather-Display#238]
I have a pig problem with the contrast. Display 075BN-T7 V2
I use the e-Paper ESP32 Driver Board from Waveshare
https://github.com/G6EJD/ESP32-e-Paper-Weather-Display/assets/122525247/71d7b886-a43a-46aa-bd05-e0891ce6f722

**Comment by Stebe242** [comment]
ok i will try another Display. 
Do you also plan a 7 color version? Or is it possible to use such a diplay?

**Comment by G6EJD** [comment]
The text comes from OpenWeatherMap so they must have an issue or are using a slightly different spelling. Easily fixed once you know what they sending. Maybe they have changed ‘clouds’ to ‘Clouds’

**Comment by G6EJD** [comment]
Colour version, no plans because it uses too much energy and takes too long to update. It’s easy to do just replace the display and use a new driver object for it and then change the colours in the code as required. Each time a display statement is issued it has a colour parameter all black and white at the present.

**Comment by Stebe242** [comment]
Same Problem with new Display and new Controller

**Comment by G6EJD** [comment]
Have you tried the GxEPD2 gfx example in that library?
Your dependency is the library author providing support for a display that has been updated.

**Comment by Stebe242** [comment]
The Problem was the little switch 

![grafik](https://github.com/G6EJD/ESP32-e-Paper-Weather-Display/assets/122525247/d827e44e-cb6e-4e28-8a9f-e5f9269962fd)
