### ISSUE TITLE
Busy Timeout!

### ISSUE THREAD

**Issue by schroepfer** [G6EJD/ESP32-e-Paper-Weather-Display#70]
Hello,
i use your newest V16.4 and have problems to connect. 16.3 works correct.
It runs on a TTGO ESP32-WROVER.

ets_ Jun  8 2016 00:22:57
rst:0x10 (RTCWDT_RTC_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:9232
load:0x40080400,len:6400
entry 0x400806a8
Connecting to: FRITZ2
WiFi connected at: 192.168.8.102
Busy Timeout!
Entering 157-secs of sleep time
Awake for : 19.987-secs
Starting deep-sleep _period...

and here:
....
Icon name: 04n
Icon name: 04d
Voltage = 4.17
Busy Timeout!
_PowerOn : 10001028
Busy Timeout!
_Update_Full : 10001015
Busy Timeout!
_PowerOff : 10001015
Entering 860-secs of sleep time
Awake for : 41.301-secs
Starting deep-sleep period...

**Comment by G6EJD** [comment]
Interesting as there is little difference, in fact no difference in the http fetch functions. I did change the time server to the recommended ‘pool.ntp.org’ rather than a specific ‘0.europe.pool.ntp.org’ or ‘0.de.pool.ntp.org’ but getting time is early in the start-up, so not that.
I’ll do some difference checks and test it this morning. Thanks.

**Comment by schroepfer** [comment]
in the WAVESHARE_2_9 example i get the same problem:

Connecting to: FRITZ2
WiFi connected at: 192.168.8.104
Failed to obtain time
Busy Timeout!
Entering 1800-secs of sleep time
Awake for : 18.999-secs
Starting deep-sleep period...

but i changed the 5 sec to 15 and it worked!
   while (!getLocalTime(&timeinfo, 5000)) { // Wait for 5-sec for time to synchronise

**Comment by G6EJD** [comment]
Thanks for the feedback. I assume your using the top-level pool NTP server address in the credentials file
default 'pool.ntp.org' ? Which is what they recommend, but I'm thinking that address is taking a long time to be resolved and hence the need to increase connection time-out, it should connect in millis-secs.
Please try '0.de.pool.ntp.org' in the credential file. That is a more direct route to your nearest time server. Or 1.de.pool.ntp.org Or 2.de.pool.ntp.org

**Comment by schroepfer** [comment]
I use this one:
configTime(0, 0, "0.de.pool.ntp.org", "3.de.pool.ntp.org");

**Comment by G6EJD** [comment]
Yes, those are your local time-servers so best solution. The NTP Pool advice works but takes too long to resolve the address. BTW ideally set the 0,0 to GMToffset, DSTOffset.

I'm changing the credentials text and examples to reflect this, thanks for your help.

**Comment by schroepfer** [comment]
I changed it to: (in your newest Waveshare_7_5)

const char* ntpServer   = "1.de.pool.ntp.org";
int   gmtOffset_sec     = 0;  
int  daylightOffset_sec = 3600; 

here the result: (it doesn't update)  :-(
....
Icon name: 04d
Icon name: 04d
Voltage = 4.19
Busy Timeout!
_PowerOn : 10001028
Busy Timeout!
_Update_Full : 10001015
Busy Timeout!
_PowerOff : 10001015
Entering 1710-secs of sleep time
Awake for : 40.294-secs
Starting deep-sleep period...

**Comment by G6EJD** [comment]
Interesting, actually it got time OK, but that Busy TimeOut error is as a result of getting trying to get Forecast Weather. So your country code is DE and Language DE ?
This could be a OWM server issue at the moment, I've seen it many times, that Weather data is always received, but Forecast data is not.

**Comment by schroepfer** [comment]
yes DE and DE. I'l try another coutry.

**Comment by G6EJD** [comment]
I’ve just checked my two (7.7 and 4.2”) and they both show no connection to OWM so I think that’s the (OWM) issue. I’m going to report errors on screen so it’s possible to know what’s going wrong as a next update.

**Comment by schroepfer** [comment]
This is a realy good idea!

**Comment by schroepfer** [comment]
It is runng now!
I must use the LOLIN 32 PRO for correct working with my TTGO ESP-32 WROVER.
But: it doesn't wake up from deepsleep. Only when i press the reset-button!?

**Comment by AWSW2017** [comment]
Hi, I think I have the same „too“-deep sleep issue too. I updated yesterday to 16.4 and it seems that it does not wake up after some cycles/hours.

With the before used 16.0 version I think it stopped after about 3 days and needed a reset click. 

I read about this deep sleep problem somewhere else and there a hint was named that after the Serial.begin(115200) command line you should add a at least 500ms delay to fix this. Within my own sketches I followed this and they seem to work... maybe a hint for this too?

**Comment by schroepfer** [comment]
Thank you! I will try this tomorrow and tell you if it helped.

**Comment by G6EJD** [comment]
@AWSW2017 I've added a delay after Serial.begin to see if that improves reliability, plus I've added an error log facility, I'll upload it soon. Thanks for your help.

**Comment by schroepfer** [comment]
https://github.com/AWSW2017 
Hello, i inserted 1sec delay after Serial.begin and it did **not** help! He doesn't wake up.
I addet a 470uF capacitor on the 3.3V of my WROVER and it did not help to wake up!
It definitely has to do something with the power supply:
When i plug in an USB-power supply, it wake up every 1/2 hour!

I will test another ESP32. Can you recommend a good one?

**Comment by G6EJD** [comment]
A lot depends on the load placed on the on-board regulator most are designed for 500mA typical maximum with an absolute maximum of 800mA.

A key factor of all regulators is the drop-out voltage v load current, on my Lolin D32 it uses an NE6211 regulator and the data sheet says at 500mA load, the drop-out voltage rises to 700mV. So input voltage to the regulator needs to be 3.3 + 0.7 = 4.0v which can be achieved if a fully charged Li-ion/Lipo battery is used, but a battery at its nominal 3.8v will result in an ESP32 supply voltage at load of 3.8-0.7=3.1v so starting to go out of device specifications.
Given the ESP32 alone requires a peak current of 450mA when the RF stage is working, which occurs in the very early stages of switch on from sleep I understand why delays are being considered.

You could use a capacitor to provide the energy when there is load demand (See: http://g6ejd.dynu.com/index.php/micro-controllers/calculate-smoothing-capacitor-values/) but for a 1A peak lasting for 50mS you would require 250,000uF to give you an idea of the problem.

Ideally remove any loads and see if the bare (monitor the serial port) starts after sleep with no load, if so you know where the problem is. If needs be provide a separate regulator.

If applying USB power solves the problem then it is your regulator dropping out due to excess load and for battery supplies you need a higher voltage, but this is difficult, say 2x18650 in series would give you a nominal 7.6v input BUT most regulators have maximum Vin of 6.5v - so that’s not a solution. Using Nicads or Nmih say 4 in series gives 4.8v which would solve the problem, but at lower capacity of say 2400mAHr unless 8 batteries (2x4 in parallel- series) were used, but a lot of space needed!

Conclusion- it’s not a software issue it’s a voltage regulator problem, but not easy to solve for a development board with surface mount regulators, I also doubt there’s a product that can achieve a high load current LDO solution and the NE6211 is the best available. If you have any devices connected to the ESP32 power them separately via their own regulator.

**Comment by schroepfer** [comment]
I could'nt find anything about the NE6211.
But i found the datasheet of my working eBox-Board: [(https://cdn-shop.adafruit.com/product-files/3081/mic5219.pdf](url)
I thing, it is nearly the same and available. [https://lcsc.com/search?q=mic5219](url)

**Comment by G6EJD** [comment]
Apple spellchecker problem ME6211 or https://datasheet.lcsc.com/szlcsc/Nanjing-Micro-One-Elec-ME6211C33M5G-N_C82942.pdf

**Comment by G6EJD** [comment]
Yes the Adafruit regulator is good one, but only can supply 500mA the ME6211 on the Lolin D32 is 800mA.

**Comment by schroepfer** [comment]
This ist not correct. The datasheet of the ME6211C33 says max.500mA. 

I looked in the schematic of the Adafruit Huzzah32. There is a [AP2112-3.3](https://www.diodes.com/assets/Datasheets/AP2112.pdf) 
This has a Vdrop typ=250mV at 600mA. Realy nice!

**Comment by G6EJD** [comment]
Yes, sorry about that, I was looking at another device then. I just used the Mouser product selector and used 3.3v, 1A, 50uA quiescent current, SMA/SDO package and nothing matches on the market.

**Comment by G6EJD** [comment]
@AWSW2017 I think as we learn more about what's going on, we can conclude it's not a software issue, and you've helped focus on the hardware issues that it now seems to be causing this errant behaviour, yours running for 3-days then needing to be reset could be linked to a slowly discharging battery, so there is mounting evidence that this is all supply voltage linked.

**Comment by AWSW2017** [comment]
@G6EJD Thank you for your reply. Seems to be this way. I will watch this. I transferred the sketch 16.4 with no added delay again yesterday with a slower baud rate, because I used 915000 for a try (with a good cable) and now set it to 115200 again. I will tell you if it is fixed. The battery was still at 100% after the reset after about 1.5 weeks👌 and now runs since yesterday nicely without a recharge...  

If it does not react anymore I will add some MQTT to get some log messages to my smart mirror without the need of a serial connection to the Lolin board. With this info the mirror can notify me if the device does not respond as usual by not sending the messages anymore. I have added this so far to all of my projects to have a at a glance look of all batteries levels of all devices around the house. If you are interested I can send you the changes needed to modify the weather station... 

Have a nice evening 😁

**Comment by G6EJD** [comment]
Thank you for the feedback and ideas. In the 16.5 version I uploaded yesterday I’ve added the ability to record in an error log albeit transient what went wrong and to display the reason on screen. Thanks to your lead I think we have honed in on what is causing the issues and it’s not software related. For example o very rarely suffer from any issues only when my ISP service is interrupted or as happened this week, that the OWM servers failed, but now in 16.5 it will at least say why on screen until the next scheduled wake up time.

**Comment by AWSW2017** [comment]
Thanks a lot! Just uploaded 16.5 and will leave it running on 2 displays to be sure. 

Have a nice weekend! :)

**Comment by AWSW2017** [comment]
Good morning,

where can I find the log file? Today morning 1 of the 2 did not wake up after the update at 08:00 o'clock. I kept it in the status. The last shown battery level is still 100%.

Thanks in advance.

**Comment by AWSW2017** [comment]
I have used the Reset button now. Before I could not see any output on the serial monitor.
I think it hangs in a loop, because after the reset was done, the battery showed 90% only. So it seemed to be active in the last 2 hours... Maybe this is a help... Thanks in advance.

**Comment by G6EJD** [comment]
Well I made it transient, by that I mean when errors are detected by the code they are displayed on the screen until the next update, so you’d see any detected errors on the screen over writing from the bottom up. Now I assume none were displayed, there can be up to 10 errors.
For example if the ESP32 started but could not get a WiFi connection it will display that error, or could not get time, or no weather data receiver, same for forecast data or then JSON deserialisation for weather and forecast, so what is causing the error as it dies not appear to be under program control?

**Comment by G6EJD** [comment]
The first error that can be recorded is a failed WiFi connection which will time out trying to get a connection after 15-secs, then getting time another 15-secs maximum, now as they weren’t display it suggests something went wrong before that,  like the processor did not start from sleep back to a known state. 
Interestingly my Lolin D32 never shows any errors, well apart from when the OWM servers go off line.

I’ll investigate this this morning and maybe change the error log to be a series of codes saved in EEPROM or nvram for later interrogation. The alternative is to display the error log and send the cpu to sleep for a long time  so the errors can be viewed.

**Comment by G6EJD** [comment]
It now reports why the CPU restarted or was reset, does this on screen if it gets that's far in the code!

**Comment by G6EJD** [comment]
16.7 I've now Disabled the brown-out detector, which I think is the problem your having, although this is a not a good option as if it's a PSU or grounding issue, this is not the solution rather a better PSU or grounding setup. Shorted larger cables to handle the >500mA current flow at start-up.

**Comment by AWSW2017** [comment]
Hello and thank you. I will try the new version tomorrow.

**Comment by AWSW2017** [comment]
Hello, 
just uploaded 16.7 to both screens. I will let you know. 
Both stopped 2x in the last 2 days with 16.5.
Thanks for the update.

PS: When it stops again I will add several MQTT points to track external how far it gets during an update.

**Comment by G6EJD** [comment]
Thanks for helping. To be honest I think the CPU never starts and never gets to be under programme control. You’ll see that I’ve disabled the brown-out detector but the documentation does not explain whether that is a persistent or transient change, my best guess is it is a power supply issue. I have 5 boards running this code and have yet to see any of them fail. All Lolin D32 boards.

**Comment by AWSW2017** [comment]
Hi 👋 Small update: 1 of the 2 setups stopped yesterday evening at about 23:30 o’clock. Screen was not updated anymore... After about 18.5 hours the battery went down about 60% then. So I think there runs something... in serial monitor I could not see anything... 

I will add the MQTT to log the walkthrough to the program to an external source. I’ll keep you updated. 😊

Besides that I will order some new Lolin D32 boards in China to sort out that these 2 boards might an issue.

**Comment by G6EJD** [comment]
Thank you for the update. If you have the sleep time set to 23 then the last update should be 23:30 or occasionally 23:59 if the ESP32 (inaccurate RTC) is running fast then it wakes at say 23:59:30 and still does a valid update conversely at 24:30 when the ESP32 sleeps for 30-mins it next wakes at 0:00 and goes back to sleep not updating the screen, I see that across my samples, but they always wake up and never lock.

It will be interesting to see if your MQTT reports are made as the first thing it does is get a WiFi connection or not recording an error if not then reads the time or records an error if not, then if at 23:30 or beyond would not update the Wx data but if any error was detected it would display the errors on screen. So we can conclude it woke at 00:00 and went straight back to sleep but not waking up again.

Whether switching the brown-out detector off has made s difference is difficult to ascertain, but at first analysis it made no difference. The process restart being anything other than normal would have been recorded too.

Other differences could be the power/up reset sequence and whether all the conditions are being met for normal boot after sleep.

Whether it’s the development board or not is debatable but my Lolin D32 boards don’t exhibit any failures from sleep wake-up. This is why I’ve found it difficult to replicate the problem.

Initially there were clone Wemos D32 boards being sold on AliExpress  then Wemos changed its name to Lolin and I’ve never seen the clone boards since, it could be this difference that is creating the anomaly in operation. 

Maybe a short test programme that wakes,  blinks the LED, then goes to sleep and then see how that performs to eliminate nearly all of the code I’ll programme an old silicon Rev.0 board to do that and see how it performs, I’ll let you know the outcome starting from tonight.

**Comment by AWSW2017** [comment]
You’re welcome. I have to say thanks. 😊 
Yes, I recognised that with the “no update during the set night times”. The display that started updating today morning was last updated at 23:59 yesterday. The one that stopped was last updated 23:30 the last time and was kept in this state until today 18:00 until I used the reset button.

What I find really strange is that I have 3 ePaper picture frames displaying randomly downloaded greyscale picture with the same electronic setup that run now for about 4 weeks without no issue. I also put the nightly timeout time to them during the night because I found that really clever so save some energy.

I will update the code with the MQTT and give it a try. 

Thanks a lot and have a nice evening!

**Comment by G6EJD** [comment]
It is worth checking what silicon revision your ESP32’s are as I’ve read that restarting from sleep was a problem with the Rev.0 first release, now solved in Rev.1

**Comment by G6EJD** [comment]
Out of interest, testing of an early ESP32 Lolin v1.0 board together with a do-it ESP32S shows some encouraging similarity of failures to wake-up, in that my simple sleep flash the-on-board LED then sleep again sketch (actually the same Wx code but it just flashes an LED when it wakes rather than refreshing the screen) has had errors from both boards in the form of the blue LED being stuck on at random times, not waking from sleep. Both are Rev.0 ESP32's. The do-it ESP32S board sometimes does not wake from sleep at all, but the Lolin ESP32 v1.0 board (not a D32) always appears to wake and the on-board blue LED stays illuminated and as it's configured as the EPD-CS this means it was held low (EPD selected) but it never goes on to flash the LED so never gets to be under programme control.

My Rev.1 ESP32 on the Lolin D32 boards work perfectly. Reference to various forums confirms the Rev.1 silicon did indeed fix wake-from-sleep issues and using WiFi after wake-up and more than a few other issues were resolved too.

So-far, it's looking for me like, it is an issue with Rev.0 silicon variants of the ESP32.

I'm leaving the tests running.

**Comment by AWSW2017** [comment]
Hello 👋 Thanks for all your help 😁
Just ordered 10 new LOLIN D32 V1.0.0 boards from AliExpress. Should be here within 10 days...
The naming on my actual ones says V1.0.0 too and should be original ones ordered from Amazon...

For the moment I uploaded my still super stable running sketch using the 7.5 ePaper as a random picture frame with the same nightly timeout phase to see if that continues on the circuits not constantly running the weather station... The electronics setup is the same on all of them.... I just want to be sure if the circuit has a problem. I will leave this running until the new D32 boards are here. I added MQTT messages to these all too to see in my central MagicMirror to see if they all update every hour except the night times...

Have a nice weekend 😎

**Comment by G6EJD** [comment]
Thank you for the update. My boards still haven’t failed displaying the weather due to a CPU restart error, but today all my 3 trial systems recorded a failed reception of Weather data, but Forecast was OK. This was the first time I’ve seen the error reporting work for real. The processor restart message was a normal wake from sleep status. Hopefully your new boards will improve your reliability. My boards say  V1.0.0 but they are not the same as the V1.0.0 boards I purchased about 2-years ago and which have Rev.0 silicon ESP32 fitted, they are the unreliable types.

**Comment by AWSW2017** [comment]
Hi 👋 Just a quick update: The picture frame sketch is still running on all 3 displays without a single error or timeout since 10 days.

I am still waiting for the new D32 boards. I will create a new weather station for them then and keep the picture frames running until the battery dies. Actually they are at 75% with a deep sleep timeout of 30 minutes.

Have a nice day 😎

**Comment by G6EJD** [comment]
Thank you for the update. At some point it's worth checking your ESP32's for their silicon revision either 0 or 1.  Rev.0 ESP32 is unreliable and prone to errors after sleep. The compiler gives the revision number during its first few lines (scroll-up the message output to find it).

**Comment by G6EJD** [comment]
Thank you for the update. At some point it's worth checking your ESP32's for their silicon revision either 0 or 1.  Rev.0 ESP32 is unreliable and prone to errors after sleep. The compiler gives the revision number during its first few lines (scroll-up the message output to find it).

**Comment by G6EJD** [comment]
Thank you for the update. At some point it's worth checking your ESP32's for their silicon revision either 0 or 1.  Rev.0 ESP32 is unreliable and prone to errors after sleep. The compiler gives the revision number during its first few lines (scroll-up the message output to find it).

**Comment by G6EJD** [comment]
Thank you for the update. At some point it's worth checking your ESP32's for their silicon revision either 0 or 1.  Rev.0 ESP32 is unreliable and prone to errors after sleep. The compiler gives the revision number during its first few lines (scroll-up the message output to find it).

**Comment by AWSW2017** [comment]
Test is running with the new boards:

![067D5C6A-B9C0-4D64-BB22-0AF33C69D73B](https://user-images.githubusercontent.com/34800740/62004844-a070ca80-b12a-11e9-87f2-e0abef584cdc.jpeg)

**Comment by G6EJD** [comment]
Nice set-up and a good idea to remove the long ribbon and use the shorter stub. I'm going to do that too.

Newer boards do run a lot better than older variants, but silicon revision appears to be the same.

**Comment by ag-ni** [comment]
I am having the same "busy time out" issue. I have tried increasing the timers as @schroepfer has mentioned (which solved the problem for him ) but the issue remains. I am using a 7.5 inch Waveshare paper display. The sketch uploads and it pulls data etc but the display fails. 
To eliminate the loose ribbon cable problem - I have tried uploading example sketch from Waveshare and that displays perfectly fine but when I upload this sketch, it gets uploaded, fetches data and then throws "busy timeout" error. Can someone help please. 

Regards
Shek

**Comment by G6EJD** [comment]
Did you modify the gxepd2 library to shorten the reset pulse?

**Comment by G6EJD** [comment]
The reset delay has to be 10x shorter

**Comment by ag-ni** [comment]
@G6EJD : Can you give me a hint where can I modify it please ?

**Comment by ag-ni** [comment]
I mean can  you tell me the file and parameter that needs to be modified.

**Comment by G6EJD** [comment]
The GxEPD2 code that needs to be modified, https://github.com/ZinggJM/GxEPD2/blob/master/src/GxEPD2_EPD.cpp

Scroll down to line 69 you will see the reset function there, the delay used is 20mS not 2mS. You can adjust your library file to try it out, make a back up first then reduce the 20 to 2mS

Until the GxEPD2 code is modified this is a required fix.

**Comment by ag-ni** [comment]
@G6EJD : I modified the code GxEPD2_EPD.cpp, reduced it to 2ms, recompiled and pushed, but still getting busy timeout.

**Comment by G6EJD** [comment]
All the delay(20) lines become delay(2) when you say ‘pushed’ what do you mean? Your local library copy should now be showing the shorter delays.

Are you sure the cables especially the busy line is connected.

If that doesn’t work you need to contact the GxEPD author, but unfortunately he has removed the ability to report issues, In a somewhat arrogant way!

**Comment by ag-ni** [comment]
Hi @G6EJD : Thanks a lot for responding. I have changed all the delays from 20 to 2 . When I say 'pushed', I mean compiled and uploaded the code in the esp32. 
The cables are connected properly. Because when I am checking with the Waveshare example sketch, the display works. But when I am checking with this code, I get 'busy timeout' error. I have changed the file in my local library but to no avail.

**Comment by G6EJD** [comment]
So, to recap, your using the new display HAT version? And Waveshare have said the reset pulse duration needs to be reduced which is what they have changed in their example, so the question is, which GxEPD2 library are you using when compiling have you turned on verbose mode to ensure it is coming from your libraries folder (the location of the one the modified) as it’s easy to install two versions of a library.

**Comment by ag-ni** [comment]
@G6EJD : Yes, I am using v2 display. 
Indeed its coming from the library folder where I have modified the file. I have made sure that I do not have two versions as it was the first thing in your post :-) 
Any other ideas where it could be going wrong ?

**Comment by G6EJD** [comment]
Ask @AWSW2017 how he solved it? Maybe he made other changes in the GxEPD library

**Comment by AWSW2017** [comment]
Hello 👋 
Please have a look to this entry: https://github.com/G6EJD/ESP32-e-Paper-Weather-Display/issues/102#issuecomment-630969193

All necessary changes are named there to get the V2 7.5” displays to work. Good luck

**Comment by ag-ni** [comment]
@AWSW2017 , @G6EJD : Thanks a lot for comments. Let me try it.

**Comment by G6EJD** [comment]
@ag-ni don't forget to select the correct display driver object too.

**Comment by G6EJD** [comment]
Did you get it working?

**Comment by ag-ni** [comment]
@G6EJD : Thanks for asking, I am still struggling with it. I have used your code with the modification that you and @AWSW2017 has suggested ( 20 ms -> 2 ms ). 
Also when compiling the code , it fails at line 112 - here ( || DebugDisplayUpdate). The error I am getting is "DebugDisplayUpdate' was not declared in this scope" .
I was able to compile if I delete this portion " '|| DebugDisplayUpdate ". It compiles but does not work. 
Anu suggestions will be highly appreciated.

**Comment by G6EJD** [comment]
OK, it compiles, do you see anything on the serial port when you press reset or right after programming? You should see it connect to the WiFi, then fetch all the weather data, then say going to sleep regardless of it the screen is connected/working or not.

**Comment by ag-ni** [comment]
@G6EJD : You are right. I see all that on the serial console. Only it does not show up on the display, just turns into 'Busy Timeout!'. Here is what I see with 16.7 and the same with the latest code - 

18:04:14.386 -> Icon: 02d
18:04:14.386 -> Desc: few clouds
18:04:14.386 -> CCov: 17
18:04:14.386 -> WSpd: 2.55
18:04:14.386 -> WDir: 124.00
18:04:14.386 -> Rain: 0.00
18:04:14.386 -> Snow: 0.00
18:04:14.386 -> Peri: 2020-06-20 06:00:00
18:04:14.386 -> 
18:04:14.386 -> Period-23--------------
18:04:14.386 -> Temp: 24.98
18:04:14.386 -> TLow: 24.98
18:04:14.386 -> THig: 24.98
18:04:14.386 -> Pres: 1006.00
18:04:14.386 -> Humi: 55.00
18:04:14.386 -> For0: Clouds
18:04:14.386 -> 
18:04:14.386 -> 
18:04:14.386 -> Icon: 03d
18:04:14.386 -> Desc: scattered clouds
18:04:14.386 -> CCov: 29
18:04:14.386 -> WSpd: 7.02
18:04:14.386 -> WDir: 175.00
18:04:14.386 -> Rain: 0.00
18:04:14.386 -> Snow: 0.00
18:04:14.386 -> Peri: 2020-06-20 09:00:00
18:04:14.386 -> Icon name: 03d
18:04:14.422 -> Icon name: 02n
18:04:14.422 -> Icon name: 04n
18:04:14.422 -> Icon name: 04n
18:04:14.422 -> Icon name: 04d
18:04:14.422 -> Icon name: 04d
18:04:14.422 -> Icon name: 04d
18:04:14.422 -> Icon name: 04d
18:04:14.422 -> Icon name: 04d
18:04:14.456 -> Evnt#01 : Software reset CPU
18:04:14.456 -> Evnt#02 : *** Entering Sleep ***
18:04:24.468 -> Busy Timeout!
18:04:35.253 -> Busy Timeout!

**Comment by ag-ni** [comment]
@G6EJD : I am getting this on the serial with the latest code - 

18:10:38.048 -> Icon: 03d
18:10:38.048 -> Desc: scattered clouds
18:10:38.048 -> CCov: 34
18:10:38.048 -> WSpd: 2.91
18:10:38.048 -> WDir: 66.00
18:10:38.048 -> Rain: 0.00
18:10:38.048 -> Snow: 0.00
18:10:38.048 -> Peri: 2020-06-20 03:00:00
18:10:38.048 -> 
18:10:38.048 -> Period-22--------------
18:10:38.048 -> Temp: 27.51
18:10:38.083 -> TLow: 27.51
18:10:38.083 -> THig: 27.51
18:10:38.083 -> Pres: 1005.00
18:10:38.083 -> Humi: 41.00
18:10:38.083 -> For0: Clouds
18:10:38.083 -> 
18:10:38.083 -> 
18:10:38.083 -> Icon: 02d
18:10:38.083 -> Desc: few clouds
18:10:38.083 -> CCov: 17
18:10:38.083 -> WSpd: 2.55
18:10:38.083 -> WDir: 124.00
18:10:38.083 -> Rain: 0.00
18:10:38.083 -> Snow: 0.00
18:10:38.083 -> Peri: 2020-06-20 06:00:00
18:10:38.083 -> 
18:10:38.083 -> Period-23--------------
18:10:38.083 -> Temp: 24.98
18:10:38.083 -> TLow: 24.98
18:10:38.083 -> THig: 24.98
18:10:38.083 -> Pres: 1006.00
18:10:38.083 -> Humi: 55.00
18:10:38.083 -> For0: Clouds
18:10:38.083 -> 
18:10:38.083 -> 
18:10:38.083 -> Icon: 03d
18:10:38.083 -> Desc: scattered clouds
18:10:38.083 -> CCov: 29
18:10:38.083 -> WSpd: 7.02
18:10:38.083 -> WDir: 175.00
18:10:38.083 -> Rain: 0.00
18:10:38.083 -> Snow: 0.00
18:10:38.083 -> Peri: 2020-06-20 09:00:00
18:10:38.120 -> Icon name: 03d
18:10:38.120 -> Icon name: 02n
18:10:38.158 -> Icon name: 04n
18:10:38.158 -> Icon name: 04n
18:10:38.158 -> Icon name: 04d
18:10:38.158 -> Icon name: 04d
18:10:38.158 -> Icon name: 04d
18:10:38.158 -> Icon name: 04d
18:10:38.158 -> Icon name: 04d
18:10:48.208 -> Busy Timeout!
18:10:58.647 -> Busy Timeout!
18:11:08.671 -> Busy Timeout!
18:11:08.671 -> Entering 1165-secs of sleep time
18:11:08.671 -> Awake for : 33.190-secs
18:11:08.671 -> Starting deep-sleep period...

**Comment by sek-bb** [comment]
Hello all,,

thank you very much first of all for the great project and sharing the code :-) I am very excited and hope that I can get the e-ink display working as well:

Got the Waveshare E-Ink 7.5" V2 (800x600) - code in use: Waveshare_7_5_T7

Unfortunately I get "Timeout" errors:

20:40:14.822 -> Icon name: 01n
20:40:14.869 -> Icon name: 02n
20:40:14.869 -> Icon name: 02n
20:40:14.869 -> Icon name: 03n
20:40:14.869 -> Icon name: 04n
20:40:14.869 -> Icon name: 10d
20:40:14.869 -> Icon name: 04d
20:40:14.869 -> Icon name: 04d
20:40:14.869 -> Icon name: 10n
20:40:24,896 -> Busy Timeout!
20:40:35,373 -> Busy Timeout!
20:40:45,378 -> Busy Timeout!

Is there possibly an error handling here?

Thanks and greetings
Peter

**Comment by AWSW2017** [comment]
Hello Peter 👋
Please have a look to this entry: #102 (comment)

All necessary changes are named there to get the V2 7.5” displays to work. Good luck

**Comment by G6EJD** [comment]
I have changed the code to implement the revised timing for this display it’s not obvious how to do this, but if you have a copy of the new code it should work ok. It’s all about the screen driver initialisation options.

**Comment by AWSW2017** [comment]
Cool 😎 I didn’t know this. I’ll have a look at this later. Thanks again 😁

**Comment by sek-bb** [comment]
Hello :-), yes i´m using the latest code V16.9 - is there another workaround`?

**Comment by G6EJD** [comment]
Are you using the Waveshare HAT to make a display connection?

See this:
void GxEPD2_EPD::init(uint32_t serial_diag_bitrate, bool initial, uint16_t reset_duration, bool pulldown_rst_mode)
Try:
display.init(115200, 2);

instead of:

display.init(0);

**Comment by sek-bb** [comment]
Good morning and thanks for your fast reply ...
Still the same issue:

...
07:13:07.446 -> Icon name: 10n
07:13:07.446 -> Icon name: 10n
07:13:07.446 -> Icon name: 03n
07:13:17.470 -> Busy Timeout!
07:13:17.470 -> _PowerOn : 10001035
07:13:27.971 -> Busy Timeout!
07:13:27.971 -> _Update_Full : 10001015
07:13:37.963 -> Busy Timeout!
07:13:37.963 -> _PowerOff : 10001015
07:13:37.963 -> Entering 1014-secs of sleep time
07:13:37.963 -> Awake for : 32.046-secs
07:13:37.963 -> Starting deep-sleep period...

**Comment by sek-bb** [comment]
Regarding: Are you using the Waveshare HAT to make a display connection? --> Yes

**Comment by G6EJD** [comment]
OK, this suggests either a connection setup error, so let’s start by asking exactly what display your using?
What is the interface between the ESP32 and display eg a HAT?
What pin definitions have you set in the code?
Did you change the display.init line in the code?

**Comment by sek-bb** [comment]
- In use display: Waveshare 7.5 Inch E-Paper Display HAT Module V2 Kit 800x480 Resolution 3.3v/5v E-Ink Electronic Screen with Embedded Controller SPI Interface Compatible with Raspberry Pi/Jetson Nano/Arduino/STM32 

- Like written above: HAT Module Revision 2.1

- Pin definiton like defined in spec:
// Connections for e.g. LOLIN D32
static const uint8_t EPD_BUSY = 4;  // to EPD BUSY
static const uint8_t EPD_CS   = 5;  // to EPD CS
static const uint8_t EPD_RST  = 16; // to EPD RST
static const uint8_t EPD_DC   = 17; // to EPD DC
static const uint8_t EPD_SCK  = 18; // to EPD CLK
static const uint8_t EPD_MISO = 19; // Master-In Slave-Out not used, as no data from display
static const uint8_t EPD_MOSI = 23; // to EPD DIN

- Yes - code was changed according your advice

**Comment by G6EJD** [comment]
This is what I'm using for completeness:
**PIN Definitions**
// pins_arduino.h, e.g. LOLIN D32
//static const uint8_t SS    = 5;
//static const uint8_t MOSI  = 23;
//static const uint8_t MISO  = 19;
//static const uint8_t SCK   = 18;
//static const uint8_t DC    = 17;
//static const uint8_t RST   = 16;
//static const uint8_t BUSY  = 4;

**Screen Driver Object:**
GxEPD2_BW<GxEPD2_750_T7, GxEPD2_750_T7::HEIGHT> display(GxEPD2_750_T7(/*CS=*/ SS, /*DC=*/ 17, /*RST=*/ 16, /*BUSY=*/ 4));   // 7.5" T7 B/W display

**Screen Init:**
  **display.init(115200, true, 2);** // init(uint32_t serial_diag_bitrate, bool initial, uint16_t reset_duration, bool pulldown_rst_mode)

**Comment by sek-bb** [comment]
Good morning,

thank you very much for your feedback and help - above workaround worked - display is running :-)
Looks super awesome!

Cheers,
Peter

**Comment by G6EJD** [comment]
Good to hear, I’ll make sure the source code reflects all this.

**Comment by skiphansen** [comment]
Just in case someone runs into the same problem I just did... 

I bought a Waveshare_7_5 board **a while ago** for a project just started using it today.  I spend **several hours** trying to get it to work and got nothing but the dreaded BUSY TIMEOUT!  After reading this thread and verifying **EVERYTHING** I still couldn't get it to work so I moved to the Raspberry Pi and WaveShare's demo code and still ... BUSY TIMEOUT. 

I was just about to give up thinking the display was just bad when I noticed the little shinny "V2" sticker on the display itself...

The white box the display came in is marked "640 x 384 7.5" but the display was actually a 800x480!  I tried the Waveshare_7_5_T7/ project, sure enough that was the problem!  

There was nothing wrong with my display other than the **WRONG LABEL ON THE BOX** !

Sigh...
